#pragma once

enum EBLanguageID
{
    BLANGUAGEID_UK = 0,
    BLANGUAGEID_F = 1,
    BLANGUAGEID_D = 2,
    BLANGUAGEID_E = 3,
    BLANGUAGEID_IT = 4,
    BLANGUAGEID_NL = 5,
    BLANGUAGEID_SW = 6,
    BLANGUAGEID_FIN = 7,
    BLANGUAGEID_N = 8,
    BLANGUAGEID_DK = 9,
    BLANGUAGEID_US = 10,
    BLANGUAGEID_JP = 11,
    BLANGUAGEID_PG = 12,
    BLANGUAGEID_BR = 13,
    BLANGUAGEID_KR = 14,
    BLANGUAGEID_CH = 15,
    BLANGUAGEID_TH = 16,
    BLANGUAGEID_HW = 17,
    BLANGUAGEID_PO = 18,
    BLANGUAGEID_CZ = 19,
    BLANGUAGEID_RU = 20,
    BLANGUAGEID_USS = 21,
    BLANGUAGEID_USF = 22,
    BLANGUAGEID_UNKNOWN = 23,
};

EBLanguageID bkGetSystemLanguage();
