#pragma once

#define DECLARE_INT_FSYSVAR(name, value, shortstr, str) \
    int FSYSVAR_##name##_VAL = value; \
    char* FSYSVAR_##name##_SHORTSTR = shortstr; \
    char* FSYSVAR_##name##_STR = str;

#define DECLARE_STR_FSYSVAR(name, value, shortstr, str) \
    char* FSYSSTR_##name##_VAL = value; \
    char* FSYSSTR_##name##_SHORTSTR = shortstr; \
    char* FSYSSTR_##name##_STR = str;

#define FORWARD_INT_FSYSVAR(name) \
    extern int FSYSVAR_##name##_VAL; \
    extern char* FSYSVAR_##name##_SHORTSTR; \
    extern char* FSYSVAR_##name##_STR;

#define FORWARD_STR_FSYSVAR(name) \
    extern char* FSYSSTR_##name##_VAL; \
    extern char* FSYSSTR_##name##_SHORTSTR; \
    extern char* FSYSSTR_##name##_STR;

FORWARD_INT_FSYSVAR(DISPLAY_XRES);
FORWARD_INT_FSYSVAR(DISPLAY_YRES);
FORWARD_INT_FSYSVAR(DISPLAY_BPP);
FORWARD_INT_FSYSVAR(DISPLAY_ZDEPTH);
FORWARD_INT_FSYSVAR(DISPLAY_FLAGS);
FORWARD_INT_FSYSVAR(EMULATE_PSP_CLIPPING);
FORWARD_INT_FSYSVAR(DEFAULT_HEAP_SIZE);
FORWARD_INT_FSYSVAR(BKINIT_FLAGS);
FORWARD_INT_FSYSVAR(TARGET_FPS);
FORWARD_INT_FSYSVAR(MANAGELIGHTS);
FORWARD_INT_FSYSVAR(PALMODE);
FORWARD_INT_FSYSVAR(SUPPORTED_LANGUAGES);
FORWARD_INT_FSYSVAR(DEBUGCAMERA_SWAPSTICKS);
FORWARD_INT_FSYSVAR(DEBUGCAMERA_INVERTXAXIS);
FORWARD_INT_FSYSVAR(DEBUGCAMERA_INVERTYAXIS);
FORWARD_INT_FSYSVAR(DEBUGCAMERA_PCINPUT);
FORWARD_INT_FSYSVAR(DEBUGPAD);
FORWARD_INT_FSYSVAR(SHOWFPS);
FORWARD_INT_FSYSVAR(SHOWHEAP);
FORWARD_INT_FSYSVAR(SHOWSAFEFRAME);
FORWARD_INT_FSYSVAR(HEAPPOOLING);
FORWARD_INT_FSYSVAR(DISPLAY_FULLSCREEN);
FORWARD_INT_FSYSVAR(VERBOSELEVEL);
FORWARD_INT_FSYSVAR(PARENTWINDOW);
FORWARD_INT_FSYSVAR(USE_NET_COMMS);
FORWARD_INT_FSYSVAR(SHAREDVERTS_2D);
FORWARD_INT_FSYSVAR(SHAREDVERTS_3D);
FORWARD_INT_FSYSVAR(MOUSEGUI);
FORWARD_INT_FSYSVAR(RESOURCELINKS);
FORWARD_INT_FSYSVAR(RENDERCALLBACKS);
FORWARD_INT_FSYSVAR(MAX_PACKAGES);
FORWARD_INT_FSYSVAR(MAX_STREAMS);
FORWARD_INT_FSYSVAR(RESERVED_BLOCK_GROUPS);
FORWARD_INT_FSYSVAR(NO_SPLASH);
FORWARD_INT_FSYSVAR(NO_LOGO);
FORWARD_INT_FSYSVAR(PROPERTYTASKPOOL);

FORWARD_STR_FSYSVAR(LANGUAGE);
FORWARD_STR_FSYSVAR(DEFAULTWORLD);
FORWARD_STR_FSYSVAR(DEBUGFONT);
FORWARD_STR_FSYSVAR(HOSTASSETS);
FORWARD_STR_FSYSVAR(DEBUGCAMERA);
FORWARD_STR_FSYSVAR(DEBUGCAMERA2);
FORWARD_STR_FSYSVAR(APPLICATION_NAME);

extern char* fSysStrPtr;
