import re
import os
import argparse

parser = argparse.ArgumentParser(description="Split DWARF data by compilation units")
parser.add_argument("dwarf", type=str, help="DWARF CPP file generated by dtk")
parser.add_argument("output_dir", type=str, help="Output directory")
args = parser.parse_args()

split_pattern = re.compile(r'/\*\n(.*?)\*/(.*?)(?=/\*\n|\Z)', re.DOTALL)
compile_unit_pattern = re.compile(r'Compile unit: .*[\/\\]([\d\w]*\.\w*)')

def split_units(text: str, output_dir: str):
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    for match in split_pattern.finditer(text):
        unit_info = match.group(1)
        unit_code = match.group(2)

        unit_name_match = compile_unit_pattern.search(unit_info)
        if unit_name_match is None:
            print(f"SKIPPING: \n{unit_info}")
            continue

        unit_path = os.path.join(output_dir, unit_name_match.group(1))
        with open(os.path.join(output_dir, unit_name_match.group(1)), "wb") as f:
            f.write(f"/*\n{unit_info}*/".encode("utf-8"))
            f.write(unit_code.encode("utf-8"))
        print(f"Wrote {unit_path}")

with open(args.dwarf, "rb") as f:
    content = f.read().decode("utf-8")
    split_units(content, os.path.normpath(args.output_dir))
